accounts/urls.py
from django.urls import path
from accounts import views

app_name = 'accounts'



urlpatterns = [

    path('login/', views.login_view, name='login'),
    path('register/', views.register_view, name='register'),
    path('logout/', views.logout_view, name='logout'),
]

blogs/urls.py
from django.urls import path

from . import views

app_name = "blogs"




urlpatterns = [
    path('all/', views.BlogListView.as_view(), name='blogs-list'),
    path('detail/<slug:slug>/', views.BlogDetailView.as_view(), name='blog-detail'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('courses.urls', namespace='courses')),
    path('blogs/', include('blogs.urls', namespace='blogs')),
    path('accounts/', include('accounts.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

courses/urls.py
from django.urls import path
from . import views

app_name = 'courses'

urlpatterns = [
    path('', views.HomeView.as_view(), name='index'),
    path('courses/', views.courses, name='courses'),
    path('course-detail/', views.course_detail, name='course-detail'),
]

courses/models.py
from datetime import time, timedelta

from django.contrib.auth import get_user_model
from django.db import models
from django.utils.text import slugify


User = get_user_model()


class Category(models.Model):
    name = models.CharField(max_length=255, unique=True)
    image = models.ImageField(upload_to="category/images/")
    slug = models.SlugField(unique=True, null=True, blank=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name


class Course(models.Model):
    name = models.CharField(max_length=255)
    image = models.ImageField(upload_to="courses/images/")
    price = models.DecimalField(max_digits=10, decimal_places=2)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name="courses", null=True, blank=True)
    slug = models.SlugField(unique=True, blank=True)
    teachers = models.ManyToManyField('Teacher', blank=True, related_name='courses')

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name

    def get_all_duration(self):
        lessons = self.lessons.all()
        total_seconds = sum(
            lesson.video_duration.hour * 3600 + lesson.video_duration.minute * 60 + lesson.video_duration.second
            for lesson in lessons
        )
        return timedelta(seconds=total_seconds)

    def get_average_rating(self):
        comments = self.comments.all()
        if comments:
            sum_rating = sum(
                comment.rating
                for comment in comments
            )
            return sum_rating / len(comments)
        return 5



class Lesson(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name="lessons")
    title = models.CharField(max_length=255)
    video = models.FileField(upload_to="lessons/videos/")
    video_duration = models.TimeField(default=time(0, 0, 0))  # Default 00:00:00
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.course.name} - {self.title}"


class CourseComment(models.Model):

    class RatingChoice(models.IntegerChoices):
        ONE = 1
        TWO = 2
        THREE = 3
        FOUR = 4
        FIVE = 5

    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name="comments")
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="course_comments")
    rating = models.PositiveIntegerField(choices=RatingChoice.choices, default=RatingChoice.FIVE.value)
    comment = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username} - {self.course.name} ({self.rating})"


class Teacher(models.Model):
    fullname = models.CharField(max_length=50)
    photo = models.ImageField(upload_to='teachers/photos/')
    direction = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='teachers')

    def __str__(self):
        return self.fullname

courses/views.py
from django.db.models import Count
from django.shortcuts import render
from django.views import View

from courses.models import Category, Course, Teacher, CourseComment


class HomeView(View):
    def get(self, request):
        top_categories = Category.objects.annotate(course_count=Count('courses')).order_by('-course_count')[:8]
        top_courses = Course.objects.annotate(pupils_count=Count('pupils')).order_by('-pupils_count')[:6]
        top_teachers = Teacher.objects.annotate(courses_count=Count('courses')).order_by('-courses_count')[:4]
        top_comments = CourseComment.objects.filter(rating=5).order_by('-created_at')[:3]

        context = {
            'top_categories': top_categories,
            'top_courses': top_courses,
            'top_teachers': top_teachers,
            'top_comments': top_comments,
        }

        return render(request, 'courses/index.html', context)

def courses(request):
    return render(request, 'courses/courses.html')

def course_detail(request):
    return render(request, 'courses/course-detail.html')

courses/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>ECOURSES - Course Detail</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="Free HTML Templates" name="keywords">
    <meta content="Free HTML Templates" name="description">

    <!-- Favicon -->
    <link href="{% static 'courses/img/favicon.ico' %}" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap" rel="stylesheet">

    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="{% static 'courses/lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'courses/css/style.css' %}" rel="stylesheet">
</head>

<body>
    <!-- Topbar Start -->
    <div class="container-fluid d-none d-lg-block">
        <div class="row align-items-center py-4 px-xl-5">
            <div class="col-lg-3">
                <a href="" class="text-decoration-none">
                    <h1 class="m-0"><span class="text-primary">E</span>COURSES</h1>
                </a>
            </div>
            <div class="col-lg-3 text-right">
                <div class="d-inline-flex align-items-center">
                    <i class="fa fa-2x fa-map-marker-alt text-primary mr-3"></i>
                    <div class="text-left">
                        <h6 class="font-weight-semi-bold mb-1">Our Office</h6>
                        <small>123 Street, New York, USA</small>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 text-right">
                <div class="d-inline-flex align-items-center">
                    <i class="fa fa-2x fa-envelope text-primary mr-3"></i>
                    <div class="text-left">
                        <h6 class="font-weight-semi-bold mb-1">Email Us</h6>
                        <small>info@example.com</small>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 text-right">
                <div class="d-inline-flex align-items-center">
                    <i class="fa fa-2x fa-phone text-primary mr-3"></i>
                    <div class="text-left">
                        <h6 class="font-weight-semi-bold mb-1">Call Us</h6>
                        <small>+012 345 6789</small>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Topbar End -->


    <!-- Navbar Start -->
    <div class="container-fluid">
        <div class="row border-top px-xl-5">
            <div class="col-lg-3 d-none d-lg-block">
                <a class="d-flex align-items-center justify-content-between bg-secondary w-100 text-decoration-none" data-toggle="collapse" href="#navbar-vertical" style="height: 67px; padding: 0 30px;">
                    <h5 class="text-primary m-0"><i class="fa fa-book-open mr-2"></i>Bo'limlar</h5>
                    <i class="fa fa-angle-down text-primary"></i>
                </a>
                <nav class="collapse position-absolute navbar navbar-vertical navbar-light align-items-start p-0 border border-top-0 border-bottom-0 bg-light" id="navbar-vertical" style="width: calc(100% - 30px); z-index: 9;">
                    <div class="navbar-nav w-100">
                        {% for category in categories %}
                            <a href="" class="nav-item nav-link">{{ category.name }}</a>
                        {% endfor %}
                    </div>
                </nav>
            </div>
            <div class="col-lg-9">
                <nav class="navbar navbar-expand-lg bg-light navbar-light py-3 py-lg-0 px-0">
                    <a href="{% url 'courses:index' %}" class="text-decoration-none d-block d-lg-none">
                        <h1 class="m-0"><span class="text-primary">E</span>COURSES</h1>
                    </a>
                    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
                        <div class="navbar-nav py-0">
                            <a href="{% url 'courses:index' %}" class="nav-item nav-link">Home</a>
                            <a href="about.html" class="nav-item nav-link">About</a>
                            <a href="{% url 'courses:courses' %}" class="nav-item nav-link active">Courses</a>
                            <a href="teacher.html" class="nav-item nav-link">Teachers</a>
                            <a href="{% url 'blogs:blogs-list' %}" class="nav-item nav-link">Blogs</a>
                            <a href="contact.html" class="nav-item nav-link">Contact</a>
                        </div>

<!--                        <div>-->
<!--                            <a href="{% url 'accounts:login' %}" class="nav-item nav-link">Login</a>-->
<!--                            <a href="{% url 'accounts:register' %}" class="nav-item nav-link">Register</a>-->
<!--                        </div>-->

                            {% if user.is_authenticated %}
                                <div style="margin-left: 20px">
                                    <form method="post" action="{% url 'accounts:logout' %}">
                                        {% csrf_token %}
                                    <button type="submit" class="btn btn-primary">Logout</button>
                                    </form>
                                </div>
                                <div style="margin-left: 20px">
                                    <h3>{{ user.email }}</h3>
                                </div>
                            {% else %}
                                <div style="margin-left: 20px">
                                    <a href="{% url 'accounts:login' %}" class="btn btn-primary">Login</a>
                                    <a href="{% url 'accounts:register' %}" class="btn btn-primary">Register</a>
                                </div>
                            {% endif %}

                    </div>
                </nav>
            </div>
        </div>
    </div>
    <!-- Navbar End -->

    {% block content %}
    {% endblock content %}

    <!-- Footer Start -->
    <div class="container-fluid bg-dark text-white py-5 px-sm-3 px-lg-5" style="margin-top: 90px;">
        <div class="row pt-5">
            <div class="col-lg-7 col-md-12">
                <div class="row">
                    <div class="col-md-6 mb-5">
                        <h5 class="text-primary text-uppercase mb-4" style="letter-spacing: 5px;">Get In Touch</h5>
                        <p><i class="fa fa-map-marker-alt mr-2"></i>123 Street, New York, USA</p>
                        <p><i class="fa fa-phone-alt mr-2"></i>+012 345 67890</p>
                        <p><i class="fa fa-envelope mr-2"></i>.com</p>
                        <div class="d-flex justify-content-start mt-4">
                            <a class="btn btn-outline-light btn-square mr-2" href="#"><i class="fab fa-twitter"></i></a>
                            <a class="btn btn-outline-light btn-square mr-2" href="#"><i class="fab fa-facebook-f"></i></a>
                            <a class="btn btn-outline-light btn-square mr-2" href="#"><i class="fab fa-linkedin-in"></i></a>
                            <a class="btn btn-outline-light btn-square" href="#"><i class="fab fa-instagram"></i></a>
                        </div>
                    </div>
                    <div class="col-md-6 mb-5">
                        <h5 class="text-primary text-uppercase mb-4" style="letter-spacing: 5px;">Our Courses</h5>
                        <div class="d-flex flex-column justify-content-start">
                            <a class="text-white mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Web Design</a>
                            <a class="text-white mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Apps Design</a>
                            <a class="text-white mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Marketing</a>
                            <a class="text-white mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Research</a>
                            <a class="text-white" href="#"><i class="fa fa-angle-right mr-2"></i>SEO</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-5 col-md-12 mb-5">
                <h5 class="text-primary text-uppercase mb-4" style="letter-spacing: 5px;">Newsletter</h5>
                <p>Subscribe to our newsletter to get the latest updates and offers</p>
                <div class="w-100">
                    <div class="input-group">
                        <input type="text" class="form-control border-light" style="padding: 30px;" placeholder="Your Email Address">
                        <div class="input-group-append">
                            <button class="btn btn-primary px-4">Sign Up</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container-fluid bg-dark text-white border-top py-4 px-sm-3 px-md-5" style="border-color: rgba(256, 256, 256, .1) !important;">
        <div class="row">
            <div class="col-lg-6 text-center text-md-left mb-3 mb-md-0">
                <p class="m-0 text-white">&copy; <a href="#">Domain Name</a>. All Rights Reserved. Designed by <a href="https://htmlcodex.com">HTML Codex</a>
                </p>
            </div>
            <div class="col-lg-6 text-center text-md-right">
                <ul class="nav d-inline-flex">
                    <li class="nav-item">
                        <a class="nav-link text-white py-0" href="#">Privacy</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white py-0" href="#">Terms</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white py-0" href="#">FAQs</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white py-0" href="#">Help</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <!-- Footer End -->


    <!-- Back to Top -->
    <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="fa fa-angle-double-up"></i></a>


    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'courses/lib/easing/easing.min.js' %}"></script>
    <script src="{% static 'courses/lib/owlcarousel/owl.carousel.min.js' %}"></script>

    <!-- Contact Javascript File -->
    <script src="{% static 'courses/mail/jqBootstrapValidation.min.js' %}"></script>
    <script src="{% static 'courses/mail/contact.js' %}"></script>

    <!-- Template Javascript -->
    <script src="{% static 'courses/js/main.js' %}"></script>
    <script src="{% static 'courses/js/custom.js' %}"></script>
    <script src="{% static 'courses/js/custom_login.js' %}"></script>
    <script src="{% static 'courses/js/custom_register.js' %}"></script>
</body>

</html>